name: Node.js CI test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Build and lint with ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Make lint
        run: make lint

      - name: Make build
        run: make
